name = "SummationByPartsOperators"
uuid = "9f78cca6-572e-554e-b819-917d2f1cf240"
author = ["Hendrik Ranocha"]
version = "0.5.46"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
PolynomialBases = "c74db56a-226d-5e98-8bb0-a6049094aeea"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrayInterface = "0d7ed370-da01-4f52-bd93-41d350b8b718"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unrolled = "9602ed7d-8fef-5bc8-8597-8f21381861e8"

[weakdeps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[extensions]
SummationByPartsOperatorsBandedMatricesExt = "BandedMatrices"
SummationByPartsOperatorsDiffEqCallbacksExt = "DiffEqCallbacks"
SummationByPartsOperatorsForwardDiffExt = "ForwardDiff"
SummationByPartsOperatorsStructArraysExt = "StructArrays"

[compat]
ArgCheck = "1, 2.0"
AutoHashEquals = "0.2, 1, 2"
BandedMatrices = "0.17"
DiffEqCallbacks = "2"
FFTW = "1"
ForwardDiff = "0.10"
LoopVectorization = "0.12.22"
MuladdMacro = "0.2"
PolynomialBases = "0.4.15"
PrecompileTools = "1.0.1"
RecursiveArrayTools = "2.11"
Reexport = "0.2, 1.0"
Requires = "0.5.2, 1"
SciMLBase = "1.51"
SimpleUnPack = "1"
StaticArrayInterface = "1"
StaticArrays = "1.0"
StructArrays = "0.6"
Unrolled = "0.1.3"
julia = "1.6"

[extras]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
