name = "SummationByPartsOperators"
uuid = "9f78cca6-572e-554e-b819-917d2f1cf240"
author = ["Hendrik Ranocha"]
version = "0.4.2"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PolynomialBases = "c74db56a-226d-5e98-8bb0-a6049094aeea"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Unrolled = "9602ed7d-8fef-5bc8-8597-8f21381861e8"

[compat]
ArgCheck = "1, 2.0"
DiffEqBase = "6"
DiffEqCallbacks = "2.6"
FFTW = "1"
Parameters = "0.12"
PolynomialBases = "0.4.5"
Reexport = "0.2"
Requires = "0.5.2, 1"
StaticArrays = "1.0"
Unrolled = "0.1.3"
julia = "1.4"

[extras]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BandedMatrices", "DiffEqCallbacks", "LinearAlgebra", "OrdinaryDiffEq", "SparseArrays", "SpecialFunctions", "Test"]
